language: php
php:
    - '7.4snapshot'
    - nightly
matrix:
    allow_failures:
        - php: nightly
before_script: composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_success:
     - bash <(curl -s https://codecov.io/bash)
