name: Periodic CI

on:
  schedule:
    - cron: '0 1 * * 0'
  push:
    paths:
      - '.github/workflows/periodic.yml'

jobs:
  blackbox:
    uses: innmind/github-workflows/.github/workflows/coverage.yml@main
    secrets: inherit
    with:
      tags: ci
      os: ubuntu-latest
      php-version: '8.3'
